#!/usr/bin/env python3

import sys
import time
import array
import cos_sim

def main():
    repeat = int(sys.argv[1])
    size = int(sys.argv[2])

    with open(sys.argv[3]) as f:
        vector_a = array.array('d', [float(x) for x in f.readlines()])

    with open(sys.argv[4]) as f:
        vector_b = array.array('d', [float(x) for x in f.readlines()])

    avg_runtime = 0
    similarity = None

    for i in range(repeat):
        start = time.monotonic()
        similarity = cos_sim.get_cosine_similarity(vector_a, vector_b)
        end = time.monotonic()
        avg_runtime += (end-start)

    avg_runtime = avg_runtime / repeat

    sys.stdout.write('{} {}'.format(similarity, avg_runtime))

if __name__ == '__main__':
    main()
